// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subscription.Infrastructure.Data;

#nullable disable

namespace Subscription.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512095218_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Subscription.Domain.Entities.CompanySubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionPackageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("Subscription.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPackages");

                    b.HasData(
                        new
                        {
                            Id = "93fc1c53-0c61-4f4d-b02e-82d94310a2e6",
                            Code = "bronze",
                            DurationInDays = 30,
                            Name = "Bronze",
                            Price = 0.0
                        },
                        new
                        {
                            Id = "c4a18e01-2d9f-4e4f-9a30-0b5eab0e24b0",
                            Code = "silver",
                            DurationInDays = 30,
                            Name = "Silver",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = "b2f0b276-6b39-45b6-9db8-c6fe7aab889e",
                            Code = "gold",
                            DurationInDays = 30,
                            Name = "Gold",
                            Price = 199.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
